### ISSUE TITLE
general help

### ISSUE THREAD

**Issue by tamih** [tixif-ni/ngx-localforage#9]
Hi ,
I am trying to use ngx-localforage in my angualr4 project that uses node.js
I need it to work online and offline and need some help : 
1. is ngx-localforage support the same Browsers Platformsas as localforage support ? 
[https://github.com/localForage/localForage/wiki/Supported-Browsers-Platforms](url)

2. Is there any example code of  angular project that uses it ? 

thanks 
Tami

**Comment by Xepe** [comment]
Hello, 

1. Yes
2. at the moment we don't have a example project, but the readme was updated

Regards
